version: "3.8"
services:
  mysqldb-notes:
    restart: always
    image: mysql:8.0
    container_name: mysqldb-notes
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notesdb
      MYSQL_USER: nithin
      MYSQL_PASSWORD: nithin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost","-uroot","-proot"]
      timeout: 10s
      retries: 10
    ports:
      - "3308:3306"
    volumes:
      - mysqldb_data:/var/lib/mysql
  mynotesapp:
    build: .
    image: nithingowda46/notes-app:latest
    env_file:
      - .env
    container_name: mynotesapp
    depends_on:
        mysqldb_notes:
          condition: service_healthy
    ports:
      - "8000:8000"
volumes:
  mysqldb_data:
